### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by suhmantha1** [kylestetz/metaphorpsum#2]
yo @kylestetz any chance of being able to specify a json format response instead of plain text?
k byyyyyye

**Comment by kylestetz** [comment]
:wave: yes!

This will be more or less complicated depending on the way you want the JSON to be formatted. Since metaphorpsum is built with streams, it generates the response as it is sent and thus you can't just `JSON.stringify` the output before sending it to the client.

If the structure you have in mind is something like `{"text":"<metaphorpsum generated text>"}` then there's a straightforward way to put it together: you can just push `{"text":"` out of the stream before sending the generated output, and then push `"}` before closing the stream. You'll also have to set the content type to `application/json`, probably based on the presence of a `?format=json` query parameter.

There's already a hook for the [end of the stream](https://github.com/kylestetz/metaphorpsum/blob/master/routes/index.js#L41), and a corresponding `start` flag would be good for setting the content type and pushing the initial JSON bit.

Go ahead and submit a PR :smile:
